### ISSUE TITLE
RestClient::Forbidden at /

### ISSUE THREAD

**Issue by tomconte** [johnnyhalife/waz-storage#10]
Probably a newbie issue...

sinatra.error is:

403 Forbidden: ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:b501b3d4-7c0a-47b0-817f-248ef2ab1435 Time:2011-03-17T20:54:15.7720388Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request '43JwuRyGg8g5VJISUWPmDwH4f0u4EBQUL+XSZiNhMXQ=' is not the same as any computed signature. Server used following string to sign: 'GET x-ms-date:Thu, 17 Mar 2011 20:54:15 GMT /tcontepub/json?comp=list'.</AuthenticationErrorDetail></Error>

What I am trying to do:

WAZ::Storage::Base.establish_connection!(:account_name => 'foo', :access_key => 'bar')
c = WAZ::Blobs::Container.find('json')

Running on Ruby 1.9 on Windows.
Any help appreciated!!

**Comment by johnnyhalife** [comment]
Are your access key / account key valid Azure Storage keys?

thanks,
~johnny

**Comment by tomconte** [comment]
Yup, I copy/pasted them from a working Azure SDK service configuration... Unless there is a special syntax involved?

**Comment by tomconte** [comment]
Sorry, more specifically the 403 happens when I try to access c.blobs ... c.store() works fine for example.

**Comment by tomconte** [comment]
I got it to work :-) Had to fix a couple things in list_blobs. I'll try to submit a patch :)

**Comment by johnnyhalife** [comment]
Published on 1.0.5
