### ISSUE TITLE
Needs some updates

### ISSUE THREAD

**Issue by djberg96** [johnnyhalife/waz-storage#18]
Hi,

I was going to submit some patches (I was just taking a look at Azure), but then I realized that gmontard has already forked and updated this code. Is there any chance you could merge his updates? Has he sent you a pull request?

Regards,

Dan

**Comment by johnnyhalife** [comment]
He didn't, but sure, if he sends me a pull-request I'll be glad to update, push, and publish the latest version with his changes.

/cc @gmontard

**Comment by djberg96** [comment]
I sent him an email but haven't heard anything back. You could always just "git pull https://github.com/gmontard/waz-storage". Up to you.

**Comment by johnnyhalife** [comment]
I'll let's give him a day or two, basically I'm wondering why he didn't
came back to the "master repo" might be something that breaks backward
compat or so.

On Mon, May 7, 2012 at 10:34 PM, Daniel Berger <
reply@reply.github.com

**Comment by gmontard** [comment]
Hello,

Sorry for the delay, i just sent you a pull request !

**Comment by johnnyhalife** [comment]
Hey!! Thanks to @gmontard and his pull-request (#19) it's published as waz-storage-1.1.2 on rubygems =) 

I've added @gmontard  to the README.rdoc 

![](http://puu.sh/tMDX)

And tweaked the README.rdoc a little bit

:metal: thanks :metal:

@djberg96 feel free to 

```
sudo gem update waz-storage
```

and you'll get latest changes out-of-the-box!

thanks to both of you!

**Comment by djberg96** [comment]
Great, thanks!
