### ISSUE TITLE
Queue storage sample code not working.

### ISSUE THREAD

**Issue by saksham** [johnnyhalife/waz-storage#2]
Hi,
The following code (as shown in the sample) does not seem to work. Could you please see what's wrong?

queue = WAZ::Queues::Queue.create('my-queue')
queue.clear
queue.enqueue!("Hello, world!")
messages = queue.lock() # <----- Stacktrace points me to this line
text = messages.first().message_text
p(text)

I get the following error:
RestClient::Response is not a valid input stream.  It must walk like either a String, an IO, or a Source.

Thanks in advance,
Saksham

**Comment by johnnyhalife** [comment]
Hi Saksham, 

When you do lock without parameters it returns just one message, you do:

```
queue = WAZ::Queues::Queue.ensure('my-queue-new')
queue.clear
queue.enqueue!("Hello, world!")
messages = queue.lock()
p messages.message_text
```

I tested that my self and it works, also make sure that your Azure account is working =)

thanks,
~johnny

**Comment by johnnyhalife** [comment]
Sorry, the ensure method is just a syntax's sugar for doing Find and Create if it doesn't exists

**Comment by saksham** [comment]
Hi Johnny,
Thanks for your response. However, I'm still having the same problem.

I tested the storage using .NET StorageClient library and it works fine, so I don't think it's related to the Azure account. Also, when I check the value of WAZ::Storage::Base.connected?, it returns true.

Thanks,
Saksham

**Comment by johnnyhalife** [comment]
Are you using the Gem Version of the Lib? Which version? 

I just run the following test against the source code and the latest version of the GEM

```
options = { :account_name => "my_account", 
            :access_key => "my_key" }

WAZ::Storage::Base.establish_connection!(options)

queue = WAZ::Queues::Queue.create('my-queue')
queue.clear
queue.enqueue!("Hello, world!")
messages = queue.lock() 
text = messages.message_text
p(text)
```

and it works as expected, which is your code base version? If copying and pasting the source code doesn't work, please send me the code file and backtrace to troubleshoot

thanks, 
~johnny

**Comment by saksham** [comment]
Just to add, when I enqueue a string using the enqueue! method, I cannot seem to be able to retrieve it from other Azure Storage Clients,eg. like AzureStorageExplorer from Neudesic. Any .NET code that tries to access the queue element also crashes (always get message-contents = null). Not sure where the exactly the problem might be. Does the enqueue method write to the queue immediately, or does it submit the request to Azure asynchronously?

Saksham

**Comment by saksham** [comment]
I'm using 1.0.0 version of waz-storage library. Installed it using:

gem install waz-storage --source http://gemcutter.org

I am trying to use the library in my Rails controller. Here's an excerpt from my controller:

```
WAZ::Storage::Base.establish_connection!(:account_name => "------", :access_key => "------")
if WAZ::Storage::Base.connected?
  queue = WAZ::Queues::Queue.create('my-queue')
  queue.clear
  queue.enqueue!("Hello")
  message = queue.lock()
  render :text => message.message_text
else
  render :text => "Not connected"
end
```

In my view, I get aforementioned error. Here is the stack trace:
C:/Programs/Ruby/lib/ruby/1.8/rexml/source.rb:21:in `create_from'
C:/Programs/Ruby/lib/ruby/1.8/rexml/parsers/baseparser.rb:133:in`stream='
C:/Programs/Ruby/lib/ruby/1.8/rexml/parsers/baseparser.rb:110:in `initialize'
C:/Programs/Ruby/lib/ruby/1.8/rexml/parsers/treeparser.rb:9:in`new'
C:/Programs/Ruby/lib/ruby/1.8/rexml/parsers/treeparser.rb:9:in `initialize'
C:/Programs/Ruby/lib/ruby/1.8/rexml/document.rb:227:in`new'
C:/Programs/Ruby/lib/ruby/1.8/rexml/document.rb:227:in `build'
C:/Programs/Ruby/lib/ruby/1.8/rexml/document.rb:43:in`initialize'
C:/Programs/Ruby/lib/ruby/gems/1.8/gems/waz-storage-1.0.0/lib/waz/queues/service.rb:74:in `new'
C:/Programs/Ruby/lib/ruby/gems/1.8/gems/waz-storage-1.0.0/lib/waz/queues/service.rb:74:in`get_messages'
C:/Programs/Ruby/lib/ruby/gems/1.8/gems/waz-storage-1.0.0/lib/waz/queues/queue.rb:134:in `lock'
D:/Code/Ruby/WindowsAzure/app/controllers/test_controller.rb:11:in`index'

As I said, the error points me to the line where I do:

queue.lock()

Saksham

**Comment by johnnyhalife** [comment]
Hey Saksham, 

Did you figured out, do you still having problems? If you still, could you please try to download the code (from github) and run the rake, I want to know if there's a failing test on your environment and so I can fix it....

thanks,
~johnny

**Comment by saksham** [comment]
Hi Johnny,
Still having the same problem. I'm really new to Ruby/Rails, so not sure if I am doing this right. I downloaded the source code, CD'ed o the directory and ran 'rake test --trace'. I don't see anything apart from "*\* Invoke tests (first_time, not_needed)"

Do I need to do any additional setup?

Thanks,
Saksham

**Comment by johnnyhalife** [comment]
Just do "rake" no tests needed

thanks,
~johnny

**Comment by johnnyhalife** [comment]
considering it closed
