### ISSUE TITLE
How do I connect to local dev storage?

### ISSUE THREAD

**Issue by ariofrio** [johnnyhalife/waz-storage#20]
It was not at all obvious to me how this is done. There's a `:use_devenv` option that WAZ::Storage::CoreService uses, but I don't see how to establish a connection with that option.

I've tried:

```
WAZ::Storage::Base.establish_connection :use_devenv=>true, account_name=>"devstoreaccount1", :access_key=>"Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==", :base_url=>"127.0.0.1:1001"
```

To connect to Queue Storage, but after doing that, `WAZ::Queues::Queue.find "..."` fails with:

```
SocketError: getaddrinfo: No such host is known.
```

(Local storage values from [winazurestorage.py](https://github.com/sriramk/winazurestorage/blob/master/winazurestorage.py).)

**Comment by johnnyhalife** [comment]
Have you tried?
http://blogs.southworks.net/jpgarcia/2010/01/03/azure-development-fabriq-from-a-remote-machine/

On Thu, May 24, 2012 at 4:02 AM, Andres Riofrio <
reply@reply.github.com

**Comment by ariofrio** [comment]
Wow, it worked. I forgot a 0:

```
127.0.0.1:1001
```

Should have been

```
127.0.0.1:10001
```

:)
