### ISSUE TITLE
Rails 3 error

### ISSUE THREAD

**Issue by gmontard** [johnnyhalife/waz-storage#25]
Hello,

I started migrating to Rails 3 and i've got this error with the Waz-Storage Gem : 
in `load': super: no superclass method`load' for main:Object (NoMethodError)

Do you know if it's supposed to work with Railq 3 ?

Thanks

**Comment by johnnyhalife** [comment]
Mmm I never used on Rails, have about you @bosko?

**Comment by bosko** [comment]
@gmontard can you paste part of code that uses waz-storage in Rails app which causes it to fail? You can also create gist with stack trace.

**Comment by gmontard** [comment]
Sorry i haven't seen the reply and again i'm trying to make it works on Rails, so here is my error log:
https://gist.github.com/gmontard/5281469

I'm using Rails 3.1.3 and REE....

Thanks.
