### ISSUE TITLE
WAZ::Blobs::Container.list

### ISSUE THREAD

**Issue by gabpaquin** [johnnyhalife/waz-storage#30]
Hello,

When I tried to pull the list of container from my blob storage account, I am getting the following error: 

NoMethodError: undefined method `split' for nil:NilClass
from /Users/gabriel/.rvm/gems/ruby-1.9.3-p194@r8/gems/waz-storage-1.3.2/lib/waz/storage/core_service.rb:117:in`execute'

This is because 

```
  # Lists all the containers existing on the current storage account.
  def list_containers(options = {})
    content = execute(:get, nil, options.merge(:comp => 'list'))
```

in the execute call, path is set to nil. 

could we set the execute methods for core_service.rb call to the following?

```
escaped_path = !path.nil? ? path.split("/").map{ | part | CGI.escape(part) }.join("/") : ""
```

Thanks

**Comment by johnnyhalife** [comment]
Hi Gabriel,

On the commit shown above (fbfd637) I've made a potential fix for what you say. Can you please re-try? If this works, please close this issue.

**Comment by gabpaquin** [comment]
Hi Johnny,

Thanks for your quick input, it works perfectly!
