### ISSUE TITLE
403 error using put_blob (WAZ::Blobs::Container::store) method

### ISSUE THREAD

**Issue by gabpaquin** [johnnyhalife/waz-storage#32]
If I tried to store content on the azure blobs storage I am getting a 403 error if I tried to do the following:

``` ruby
test =File.read("/Users/gabriel/code/npathway/r8_image/2005_May_second/p13a.png")
my_container = WAZ::Blobs::Container::find("images")
my_container.store("2005_may_p15",test,"image/png")
```

However if I do the following:

``` ruby
my_container = WAZ::Blobs::Container::find("images")
my_container.store("2005_may_p15","simple string","application/octet-stream")
```

I don't get the 403 error.

**Comment by smarx** [comment]
Try this:

``` ruby
open('/Users/gabriel/code/npathway/r8_image/2005_May_second/p13a.png', 'rb') do |f|
    container.store('2005_may_p15', f.read, 'image/png')
end
```

I haven't tested it, but I _think_ the fix for the underlying bug is to use `payload.bytesize` instead of `payload.size` in `SharedKeyCoreService::generate_request`. I'll give it a try and submit a pull request if I'm right.

**Comment by johnnyhalife** [comment]
please.

**Comment by smarx** [comment]
I did some minimal testing (basically just @Gabey's code above), and the fix in the pull request seems to work, in that I don't receive a 403 error.

**Comment by gabpaquin** [comment]
That works pretty well! thanks @smarx
