### ISSUE TITLE
Error loading with Rails 3

### ISSUE THREAD

**Issue by gmontard** [johnnyhalife/waz-storage#36]
Hello,

I started migrating to Rails 3 and i've got this error with the Waz-Storage Gem : 
in load': super: no superclass methodload' for main:Object (NoMethodError)

Here is the full trace : 
https://gist.github.com/gmontard/5281469

I'm using Rails 3.1.3 and REE....

Thanks for the help

**Comment by johnnyhalife** [comment]
Which version of the Gem are you using?

**Comment by gmontard** [comment]
I use the latest which is 1.3.6

**Comment by johnnyhalife** [comment]
Do you have a sample project where you can easily repro this?

**Comment by gmontard** [comment]
While creating a sample project for you, it happend to work ! strange.
So i decied to try something and put the "waz-storage" gem on top of my Gemfile, and then it worked !

Si i think there is some kind of conflict with an other Gem that i use... i'm investigating !

Thanks.

Edit : I found the conflict gem : gem "declarative_authorization"
