### ISSUE TITLE
Max file size is limited to 64mb

### ISSUE THREAD

**Issue by 0-1-0** [johnnyhalife/waz-storage#39]
Hi, 
I am using waz-storage + paperclip and faced the following problem:
Azure drops connections after 64mb data transferred. I need to upload files up to 200mb, and as I read at  Azure documentation it is only possible by chunking data and performing several requests. I am not sure, if waz-storage has such option. 
It will be great, you you can advise how to overcome this issue, or what modules can be modified, so I can send a pull request for this feature.

**Comment by johnnyhalife** [comment]
You should create a block blob and use put_block and such. Checkout the code.
