### ISSUE TITLE
Only Retrieves Containers it Creates

### ISSUE THREAD

**Issue by buddylindsey** [johnnyhalife/waz-storage#4]
I have been trying to work with blobs. However it seems that this library only seems to be able to retrieve containers it creates. I have 3 containers on my account and the only that ca be retrieved when I do Container.find is the one I created using this library. Was curios if this is a known issue or something that is on purpose.

**Comment by johnnyhalife** [comment]
Hey percent20,

Can you send me more details about this, what will ideally work is the list of containers that you have (an screenshot from the browser will work too) just to make sure this isn't an issue related to naming of those containers. Also if you can specify which container(s) are being retrieved and which not.

_This is not a known issue_ and I'll be happy to help you on this fixing it or giving you a workaround.

thanks for reporting!
~johnny

**Comment by buddylindsey** [comment]
Here is a link to the code I wrote as a test case.

http://pastebin.com/Xn2LDwEz

Here is an image of the output this produces. It lists all the containers I have which are site,show,temp.

http://www.flickr.com/photos/buddylindsey/5015167580/

If you need more info just let me know.

**Comment by johnnyhalife** [comment]
I'm not being able to reproduce it... 

Quick question: which tool did you use to create the containers?

**Comment by buddylindsey** [comment]
I used cerebrata's tool. Could it be a date issue? The containers were created around 7/20/10

http://www.cerebrata.com/Products/CloudStorageStudio/Default.aspx

**Comment by johnnyhalife** [comment]
This is fixed on the v1.0.2.

It was a problem related to an additional parameter required by the latest version of the Windows Azure Storage API, most of the third-parties are using 2009-09-19 and once a blob/container gets that version it needs another parameter called "restype" with the "X-MS-Version" header.

Now it's working! Thanks for reporting!

**Comment by buddylindsey** [comment]
Thanks for the diligence and getting it to work.
