### ISSUE TITLE
NoMethodError: undefined method `toutf8'

### ISSUE THREAD

**Issue by buddylindsey** [johnnyhalife/waz-storage#8]
I was trying to get a list of containers, well anything with containers, and got this error. I did a bit of searching and it is a common problem. To fix all that needs to be done is add:

require 'kconv'

Just thought i would throw a message to you about this.

**Comment by johnnyhalife** [comment]
Great, if you were using Ruby 1.9 that's the "fix" up to today since I'll be removing the dependency with toutf8 as on 1.9 everything is utf8 =)
