### ISSUE TITLE
undefined method `length'

### ISSUE THREAD

**Issue by buddylindsey** [johnnyhalife/waz-storage#9]
Another issue. I was trying to upload a gif using irb with this line.

blob = con.store('pew_pew.gif',File.open('pew.gif'),'image/gif')

I got the following error

NoMethodError: undefined method `length' for #File:pew.gif

I tracked it down and changed the method length to 'size' in this file:

lib/waz/storage/core_service.rb Line 26

And it worked.

Not sure if I am doing something wrong, but this is what had to do to get it to work.

Thanks for the great work.

**Comment by johnnyhalife** [comment]
I'm including your fix on 1.0.5 _to be released today_
